# Site settings
title: Tenkisi_
email: tenkisi221@gmail.com
description: "tenkisiの日記です。なんかなんでも記事にします。クソ眠いです。なぜ眠いのかというと、このサイトがまだ完成していないからです。"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tenkisi.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
kramdown:
  input: GFM

#SNS
twitter_username: ten_kisi
github_username: tenkisi
