# Site settings
title: Tenkisi_
email: tenkisi221@gmail.com
description: "tenkisiの日記です。なんかなんでも記事にします。クソ眠いです。なぜ眠いのかというと、このサイトがまだ完成していないからです。"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tenkisi.github.io" # the base hostname & protocol for your site
permalink: /:categories/:year/:month/:day/:title

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
highlighter: rouge 

#SNS
twitter_username: ten_kisi
github_username: tenkisi

host: 192.168.230.128
port: 4000
