# Site settings
title: Tenkisi_
email: tenkisi221@gmail.com
description: "tenkisi（てんきし）の日記です。なんかなんでも記事にします。何でも記事にしますとは言ったものの、意外にもネタがなくて困っております。。。"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://tenkisi.github.io" # the base hostname & protocol for your site
permalink: /:categories/:year/:month/:day/:title

#Pagination
gems: [jekyll-paginate]
paginate: 12 
paginate_path: "blog/page:num"

# Build settings
markdown: redcarpet
redcarpet:
    extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
highlighter: rouge 

#SNS
twitter_username: ten_kisi
github_username: tenkisi

#Server
host: 192.168.230.128
port: 4000
